///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Trendyol
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Case7 recording.
    /// </summary>
    [TestModule("2af6489f-b87c-4c0b-bea2-0ba7607aa49f", ModuleType.Recording, 1)]
    public partial class Case7 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolRepository repository.
        /// </summary>
        public static TrendyolRepository repo = TrendyolRepository.Instance;

        static Case7 instance = new Case7();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Case7()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Case7 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.GirişYap' at 18;16.", repo.ApplicationUnderTest.GirişYapInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.GirişYap.Click("18;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginEmail' at 163;16.", repo.ApplicationUnderTest.LoginEmailInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.LoginEmail.Click("163;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginEmail' at 163;16.", repo.ApplicationUnderTest.LoginEmailInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.LoginEmail.Click("163;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'mesutronw{LControlKey down}{RMenu down}{Qkey}{RMenu up}{LControlKey up}{LControlKey up}gmail.com{Tab}111111' with focus on 'ApplicationUnderTest.LoginEmail'.", repo.ApplicationUnderTest.LoginEmailInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.LoginEmail.PressKeys("mesutronw{LControlKey down}{RMenu down}{Qkey}{RMenu up}{LControlKey up}{LControlKey up}gmail.com{Tab}111111");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'mr' with focus on 'ApplicationUnderTest'.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Self.EnsureVisible();
            Keyboard.Press("mr");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.GirişYap1' at 61;1.", repo.ApplicationUnderTest.GirişYap1Info, new RecordItemIndex(5));
            repo.ApplicationUnderTest.GirişYap1.Click("61;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='mesutronw@gmail.com') on item 'ApplicationUnderTest.AccountNavItemUserLoginContainer.MesutronwAtgmailCom'.", repo.ApplicationUnderTest.AccountNavItemUserLoginContainer.MesutronwAtgmailComInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AccountNavItemUserLoginContainer.MesutronwAtgmailComInfo, "InnerText", "mesutronw@gmail.com");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'ApplicationUnderTest.AccountNavItemUserLoginContainer.InitialIconIUser' at 15;4.", repo.ApplicationUnderTest.AccountNavItemUserLoginContainer.InitialIconIUserInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.AccountNavItemUserLoginContainer.InitialIconIUser.Click(System.Windows.Forms.MouseButtons.Right, "15;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AccountNavItemUserLoginContainer.CıkışYap' at 45;7.", repo.ApplicationUnderTest.AccountNavItemUserLoginContainer.CıkışYapInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.AccountNavItemUserLoginContainer.CıkışYap.Click("45;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Giriş Yap') on item 'ApplicationUnderTest.AccountNavItemUserLoginContainer.GirişYap2'.", repo.ApplicationUnderTest.AccountNavItemUserLoginContainer.GirişYap2Info, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AccountNavItemUserLoginContainer.GirişYap2Info, "InnerText", "Giriş Yap");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
