///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Trendyol
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Case1 recording.
    /// </summary>
    [TestModule("744ab76b-3949-44f8-b36a-47b9c7f4e93c", ModuleType.Recording, 1)]
    public partial class Case1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolRepository repository.
        /// </summary>
        public static TrendyolRepository repo = TrendyolRepository.Instance;

        static Case1 instance = new Case1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Case1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Case1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.GirişYap' at 21;9.", repo.ApplicationUnderTest.GirişYapInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.GirişYap.Click("21;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 763;278.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Self.Click("763;278");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='E-Posta') on item 'ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.EPosta'.", repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.EPostaInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.EPostaInfo, "InnerText", "E-Posta");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Şifre') on item 'ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.Şifre'.", repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.ŞifreInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.ŞifreInfo, "InnerText", "Şifre");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Kampanyalardan haberdar olabilmem için kişisel verilerimin işlenmesini ve tarafıma elektronik ileti gönderilmesini kabul ediyorum.') on item 'ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.KampanyalardanHaberdarOlabilmemIcinK'.", repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.KampanyalardanHaberdarOlabilmemIcinKInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.KampanyalardanHaberdarOlabilmemIcinKInfo, "InnerText", "Kampanyalardan haberdar olabilmem için kişisel verilerimin işlenmesini ve tarafıma elektronik ileti gönderilmesini kabul ediyorum.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Kişisel verilerimin işlenmesine yönelik  okudum ve anladım.') on item 'ApplicationUnderTest.KişiselVerileriminIşlenmesineYoenelik'.", repo.ApplicationUnderTest.KişiselVerileriminIşlenmesineYoenelikInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ApplicationUnderTest.KişiselVerileriminIşlenmesineYoenelikInfo, "InnerText", "Kişisel verilerimin işlenmesine yönelik  okudum ve anladım.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Üye Ol') on item 'ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl'.", repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOlInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOlInfo, "InnerText", "Üye Ol");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
