///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Trendyol
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Case5 recording.
    /// </summary>
    [TestModule("e0ca276b-a3da-4882-9ed3-648e92dbccb3", ModuleType.Recording, 1)]
    public partial class Case5 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolRepository repository.
        /// </summary>
        public static TrendyolRepository repo = TrendyolRepository.Instance;

        static Case5 instance = new Case5();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Case5()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Case5 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Erkek' at 55;15.", repo.ApplicationUnderTest.ErkekInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Erkek.Click("55;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TrendyolCollectionSezonSonuFırsatl' at 253;185.", repo.ApplicationUnderTest.TrendyolCollectionSezonSonuFırsatlInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.TrendyolCollectionSezonSonuFırsatl.Click("253;185");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsCdnDsmcdnComMnresize4156221' at 18;99.", repo.ApplicationUnderTest.HttpsCdnDsmcdnComMnresize4156221Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.HttpsCdnDsmcdnComMnresize4156221.Click("18;99");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(3));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest' at 1357;59.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Self.MoveTo("1357;59");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest' at 1360;107.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Self.MoveTo("1360;107");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IHeart1' at 17;7.", repo.ApplicationUnderTest.IHeart1Info, new RecordItemIndex(6));
            repo.ApplicationUnderTest.IHeart1.Click("17;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=25,Height=22}) on item 'ApplicationUnderTest.IHeart1'.", repo.ApplicationUnderTest.IHeart1Info, new RecordItemIndex(7));
            Validate.ContainsImage(repo.ApplicationUnderTest.IHeart1Info, IHeart1_Screenshot1, IHeart1_Screenshot1_Options);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage IHeart1_Screenshot1
        { get { return repo.ApplicationUnderTest.IHeart1Info.GetScreenshot1(new Rectangle(0, 0, 25, 22)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions IHeart1_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
