///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Trendyol
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Case2 recording.
    /// </summary>
    [TestModule("ae630121-d83b-4431-add4-b2643a38d0ca", ModuleType.Recording, 1)]
    public partial class Case2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolRepository repository.
        /// </summary>
        public static TrendyolRepository repo = TrendyolRepository.Instance;

        static Case2 instance = new Case2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Case2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Case2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.GirişYap' at 15;1.", repo.ApplicationUnderTest.GirişYapInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.GirişYap.Click("15;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 816;255.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Self.Click("816;255");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (data-testid='submit-button') on item 'ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrima'.", repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrimaInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.QButtonQButtonMediumQFluidQPrimaInfo, "data-testid", "submit-button");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
