///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Trendyol
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Case3 recording.
    /// </summary>
    [TestModule("0eed2a91-3afd-462b-bf9c-df9aa5adc23e", ModuleType.Recording, 1)]
    public partial class Case3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolRepository repository.
        /// </summary>
        public static TrendyolRepository repo = TrendyolRepository.Instance;

        static Case3 instance = new Case3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Case3()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Case3 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.GirişYap' at 30;14.", repo.ApplicationUnderTest.GirişYapInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.GirişYap.Click("30;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UEyeOl' at 12;10.", repo.ApplicationUnderTest.UEyeOlInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.UEyeOl.Click("12;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeNotEqual (InnerText!='') on item 'ApplicationUnderTest.RegisterEmail'.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(2));
            Validate.AttributeNotEqual(repo.ApplicationUnderTest.RegisterEmailInfo, "InnerText", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeNotEqual (InnerText!='') on item 'ApplicationUnderTest.RegisterPasswordInput'.", repo.ApplicationUnderTest.RegisterPasswordInputInfo, new RecordItemIndex(3));
            Validate.AttributeNotEqual(repo.ApplicationUnderTest.RegisterPasswordInputInfo, "InnerText", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeNotEqual (fill!='#FFFFFF') on item 'ApplicationUnderTest.Fill1'.", repo.ApplicationUnderTest.Fill1Info, new RecordItemIndex(4));
            Validate.AttributeNotEqual(repo.ApplicationUnderTest.Fill1Info, "fill", "#FFFFFF");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeNotEqual (fill!='#FFFFFF') on item 'ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.Fill1'.", repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.Fill1Info, new RecordItemIndex(5));
            Validate.AttributeNotEqual(repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.Fill1Info, "fill", "#FFFFFF");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
