///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Trendyol
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Case4 recording.
    /// </summary>
    [TestModule("b6661279-39a9-40e5-a68f-a20d009cf5bc", ModuleType.Recording, 1)]
    public partial class Case4 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrendyolRepository repository.
        /// </summary>
        public static TrendyolRepository repo = TrendyolRepository.Instance;

        static Case4 instance = new Case4();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Case4()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Case4 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsCdnDsmcdnComMnresize2002001' at 33;21.", repo.ApplicationUnderTest.HttpsCdnDsmcdnComMnresize2002001Info, new RecordItemIndex(0));
            repo.ApplicationUnderTest.HttpsCdnDsmcdnComMnresize2002001.Click("33;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SepeteEkle' at 103;9.", repo.ApplicationUnderTest.SepeteEkleInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.SepeteEkle.Click("103;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Sepetim' at 31;9.", repo.ApplicationUnderTest.SepetimInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Sepetim.Click("31;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (value='true') on item 'ApplicationUnderTest.PbMerchantGroup.TyBgBeigeTyBorderedTyCheckboxTyI1'.", repo.ApplicationUnderTest.PbMerchantGroup.TyBgBeigeTyBorderedTyCheckboxTyI1Info, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ApplicationUnderTest.PbMerchantGroup.TyBgBeigeTyBorderedTyCheckboxTyI1Info, "value", "true");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
