///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Trendyol
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TrendyolRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("35ffee29-8413-46ce-83d9-d88e07150399")]
    public partial class TrendyolRepository : RepoGenBaseFolder
    {
        static TrendyolRepository instance = new TrendyolRepository();
        TrendyolRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        TrendyolRepositoryFolders.ChromeAppFolder _chrome;
        TrendyolRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder _entrendueruenlertuerkiyeninonlineal;
        TrendyolRepositoryFolders.ExplorerAppFolder _explorer;
        TrendyolRepositoryFolders.Explorer1AppFolder _explorer1;

        /// <summary>
        /// Gets the singleton class instance representing the TrendyolRepository element repository.
        /// </summary>
        [RepositoryFolder("35ffee29-8413-46ce-83d9-d88e07150399")]
        public static TrendyolRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TrendyolRepository() 
            : base("TrendyolRepository", "/", null, 0, false, "35ffee29-8413-46ce-83d9-d88e07150399", ".\\RepositoryImages\\TrendyolRepository35ffee29.rximgres")
        {
            _applicationundertest = new TrendyolRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _chrome = new TrendyolRepositoryFolders.ChromeAppFolder(this);
            _entrendueruenlertuerkiyeninonlineal = new TrendyolRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder(this);
            _explorer = new TrendyolRepositoryFolders.ExplorerAppFolder(this);
            _explorer1 = new TrendyolRepositoryFolders.Explorer1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("35ffee29-8413-46ce-83d9-d88e07150399")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("8386f207-1329-4cb1-ae63-ec2e115af044")]
        public virtual TrendyolRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Chrome folder.
        /// </summary>
        [RepositoryFolder("64484701-fd89-402b-b7a0-5eb491f0e994")]
        public virtual TrendyolRepositoryFolders.ChromeAppFolder Chrome
        {
            get { return _chrome; }
        }

        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAl folder.
        /// </summary>
        [RepositoryFolder("5cb22cac-0e5b-4f9b-8287-241fec31be05")]
        public virtual TrendyolRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder EnTrendUEruenlerTuerkiyeninOnlineAl
        {
            get { return _entrendueruenlertuerkiyeninonlineal; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("bc875d7d-f7bd-4bec-ba01-9500f0022fa6")]
        public virtual TrendyolRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Explorer1 folder.
        /// </summary>
        [RepositoryFolder("1a01c20e-c9ff-4a6b-9f5f-bbfda8eb32b9")]
        public virtual TrendyolRepositoryFolders.Explorer1AppFolder Explorer1
        {
            get { return _explorer1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TrendyolRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("8386f207-1329-4cb1-ae63-ec2e115af044")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            TrendyolRepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsFolder _httpswwwtrendyolcomuyelikcbeqhttps;
            TrendyolRepositoryFolders.ProductSliderStylesModuleSliderBaseFolder _productsliderstylesmodulesliderbase;
            TrendyolRepositoryFolders.PbMerchantGroupFolder _pbmerchantgroup;
            TrendyolRepositoryFolders.AccountNavItemUserLoginContainerFolder _accountnavitemuserlogincontainer;
            RepoItemInfo _girişyapInfo;
            RepoItemInfo _kişiselverileriminişlenmesineyoenelikInfo;
            RepoItemInfo _ueyeolInfo;
            RepoItemInfo _registeremailInfo;
            RepoItemInfo _registerpasswordinputInfo;
            RepoItemInfo _fill1Info;
            RepoItemInfo _sepetimInfo;
            RepoItemInfo _favorilerimInfo;
            RepoItemInfo _alışverişebaşlaInfo;
            RepoItemInfo _iheartInfo;
            RepoItemInfo _httpscdndsmcdncommnresize200200Info;
            RepoItemInfo _featuredfvInfo;
            RepoItemInfo _httpscdndsmcdncommnresize500500Info;
            RepoItemInfo _fvrtbtnInfo;
            RepoItemInfo _browsinggwhomepageInfo;
            RepoItemInfo _ufvrtbtnwrpprInfo;
            RepoItemInfo _icloseInfo;
            RepoItemInfo _buttontagfvInfo;
            RepoItemInfo _erkekInfo;
            RepoItemInfo _sepeteekleInfo;
            RepoItemInfo _httpscdndsmcdncommnresize2002001Info;
            RepoItemInfo _somebodytagInfo;
            RepoItemInfo _loginemailInfo;
            RepoItemInfo _girişyap1Info;
            RepoItemInfo _trendyolcollectionsezonsonufırsatlInfo;
            RepoItemInfo _fvrtbtn1Info;
            RepoItemInfo _httpscdndsmcdncommnresize415622Info;
            RepoItemInfo _buttontagfv1Info;
            RepoItemInfo _httpscdndsmcdncommnresize4156221Info;
            IHeart1InfoClass _iheart1Info;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "8386f207-1329-4cb1-ae63-ec2e115af044", "")
            {
                _httpswwwtrendyolcomuyelikcbeqhttps = new TrendyolRepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsFolder(this);
                _productsliderstylesmodulesliderbase = new TrendyolRepositoryFolders.ProductSliderStylesModuleSliderBaseFolder(this);
                _pbmerchantgroup = new TrendyolRepositoryFolders.PbMerchantGroupFolder(this);
                _accountnavitemuserlogincontainer = new TrendyolRepositoryFolders.AccountNavItemUserLoginContainerFolder(this);
                _girişyapInfo = new RepoItemInfo(this, "GirişYap", ".//div[#'account-navigation-container']/div/div[1]/?/?/p[@innertext='Giriş Yap']", ".//div[#'account-navigation-container']//p[@innertext='Giriş Yap']", 30000, null, "d515cc19-9ba3-4bc3-80ef-1b7a4040267f");
                _kişiselverileriminişlenmesineyoenelikInfo = new RepoItemInfo(this, "KişiselVerileriminIşlenmesineYoenelik", ".//div[#'login-register']/div[3]/?/?/form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/div[6]//div[@innertext>'Kişisel verilerimin işlenmesine']", ".//div[#'login-register']//div[@innertext>'Kişisel verilerimin işlenmesine']", 30000, null, "e4670ff4-5639-4586-89fa-b2bc6669a355");
                _ueyeolInfo = new RepoItemInfo(this, "UEyeOl", ".//div[#'login-register']/div[2]/div/button[2]/span[@innertext='Üye Ol']", ".//div[#'login-register']//span[@innertext='Üye Ol']", 30000, null, "68211e47-32b0-487a-87b9-da2357816f8a");
                _registeremailInfo = new RepoItemInfo(this, "RegisterEmail", ".//input[#'register-email']", ".//input[#'register-email']", 30000, null, "ac168977-9220-46c5-8c44-d95c3c7479cb");
                _registerpasswordinputInfo = new RepoItemInfo(this, "RegisterPasswordInput", ".//input[#'register-password-input']", ".//input[#'register-password-input']", 30000, null, "d5196012-fc75-470a-8e9f-89ac0721f32a");
                _fill1Info = new RepoItemInfo(this, "Fill1", ".//use[#'Fill-1']", ".//use[#'Fill-1']", 30000, null, "e74df106-aec3-4003-bba1-41fdb1dc56da");
                _sepetimInfo = new RepoItemInfo(this, "Sepetim", ".//div[#'account-navigation-container']/div/div[2]/a[@href>'https://www.trendyol.com/']/p[@innertext='Sepetim']", ".//div[#'account-navigation-container']//p[@innertext='Sepetim']", 30000, null, "7725cc4e-ecda-49fd-b447-598c1672cc9e");
                _favorilerimInfo = new RepoItemInfo(this, "Favorilerim", ".//div[#'account-navigation-container']/div/a[@href>'https://www.trendyol.com/']/?/?/p[@innertext='Favorilerim']", ".//div[#'account-navigation-container']//p[@innertext='Favorilerim']", 30000, null, "90dd1fb2-198d-491c-a651-6ff127e43631");
                _alışverişebaşlaInfo = new RepoItemInfo(this, "AlışverişeBaşla", ".//div[#'account-gw-favorites']/div/div[3]/div/?/?/a[@innertext='Alışverişe Başla']", ".//div[#'account-gw-favorites']//a[@innertext='Alışverişe Başla']", 30000, null, "d4d66f08-dfa3-4906-b2d6-2b54181a5bea");
                _iheartInfo = new RepoItemInfo(this, "IHeart", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[2]/div[6]/div/div/div[1]/button/i", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[2]/div[6]/div/div/div[1]/button/i", 30000, null, "c982d990-ac34-4282-a517-8202680d0f5b");
                _httpscdndsmcdncommnresize200200Info = new RepoItemInfo(this, "HttpsCdnDsmcdnComMnresize200200", ".//div[#'browsing-gw-homepage']/div/div/div/article[1]/div/div/div[2]/a[1]/img[@src='https://cdn.dsmcdn.com/mnresize/200/200/marketing/datascience/automation/2022/3/9/Top_Widget_202203091801.png']", ".//div[#'browsing-gw-homepage']//img[@src='https://cdn.dsmcdn.com/mnresize/200/200/marketing/datascience/automation/2022/3/9/Top_Widget_202203091801.png']", 30000, null, "2927de92-fb85-415b-b2b2-856b04ef9d38");
                _featuredfvInfo = new RepoItemInfo(this, "FeaturedFv", ".//div[#'account-gw-just-for-you']/div/div/div/div[1]/?/?/button", ".//div[#'account-gw-just-for-you']//button", 30000, null, "e9f3b9c8-51df-4cc2-8ae3-5a4ee1b6923e");
                _httpscdndsmcdncommnresize500500Info = new RepoItemInfo(this, "HttpsCdnDsmcdnComMnresize500500", ".//div[#'browsing-gw-homepage']/div/div/div/article[2]/div/div/div/div/a[1]/img[@src='https://cdn.dsmcdn.com/mnresize/500/500/marketing/datascience/automation/2022/6/29/SepeteEnCOkEklenenler_202206291435.png']", ".//div[#'browsing-gw-homepage']//img[@src='https://cdn.dsmcdn.com/mnresize/500/500/marketing/datascience/automation/2022/6/29/SepeteEnCOkEklenenler_202206291435.png']", 30000, null, "39cdfe03-7a8d-4a37-b71e-2c0b7ca1231d");
                _fvrtbtnInfo = new RepoItemInfo(this, "FvrtBtn", ".//div[#'search-app']/div/div[1]/div[2]/div[4]/div/div[1]/?/?/i", ".//div[#'search-app']/div/div[1]/div[2]/div[4]/div/div[1]/div[2]/i", 30000, null, "d8746459-fba3-40bc-aa86-a4a8abe46794");
                _browsinggwhomepageInfo = new RepoItemInfo(this, "BrowsingGwHomepage", ".//div[#'browsing-gw-homepage']", ".//div[#'browsing-gw-homepage']", 30000, null, "df6c200f-fddf-447a-859e-8f59e794eb51");
                _ufvrtbtnwrpprInfo = new RepoItemInfo(this, "UfvrtBtnWrppr", ".//div[#'account-gw-favorites']/div/div[3]/div/div[3]/div[4]", ".//div[#'account-gw-favorites']/div/div[3]/div/div[3]/div[4]", 30000, null, "899d4b3e-3101-4c18-882d-216ddf11422e");
                _icloseInfo = new RepoItemInfo(this, "IClose", ".//div[#'account-gw-favorites']/div/div[3]/div/div[2]/div[4]/i", ".//div[#'account-gw-favorites']/div/div[3]/div/div[2]/div[4]/i", 30000, null, "e4028100-fac7-4e3f-852d-b64114ae9177");
                _buttontagfvInfo = new RepoItemInfo(this, "ButtonTagFv", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[2]/div[6]/div/div/div[1]/button", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[2]/div[6]/div/div/div[1]/button", 30000, null, "e3713b84-3fe3-4ea0-81c8-71f7be2cc721");
                _erkekInfo = new RepoItemInfo(this, "Erkek", ".//div[#'navigation-wrapper']/nav//a[@innertext='Erkek']", ".//div[#'navigation-wrapper']//a[@innertext='Erkek']", 30000, null, "ceca5310-281f-4c32-8d60-113c0b2d9312");
                _sepeteekleInfo = new RepoItemInfo(this, "SepeteEkle", ".//div[#'search-app']/div/div[1]/div[2]/div[4]/div/div[2]//button/div[@innertext='Sepete Ekle']", ".//div[#'search-app']//div[@innertext='Sepete Ekle']", 30000, null, "e8a981ae-a2a4-4b62-9e48-6508a6416b59");
                _httpscdndsmcdncommnresize2002001Info = new RepoItemInfo(this, "HttpsCdnDsmcdnComMnresize2002001", ".//div[#'browsing-gw-homepage']/div/div[1]/div/div[2]/a[3]/img[@src='https://cdn.dsmcdn.com/mnresize/200/200/marketing/datascience/automation/2021/12/9/MpLogo_202112091740.jpg']", ".//div[#'browsing-gw-homepage']//img[@src='https://cdn.dsmcdn.com/mnresize/200/200/marketing/datascience/automation/2021/12/9/MpLogo_202112091740.jpg']", 30000, null, "0554aa36-2564-48ea-8fdd-9e2109f16df3");
                _somebodytagInfo = new RepoItemInfo(this, "SomeBodyTag", "body", "body", 30000, null, "742dd232-5379-4309-b22e-378a02b4b8b8");
                _loginemailInfo = new RepoItemInfo(this, "LoginEmail", ".//input[#'login-email']", ".//input[#'login-email']", 30000, null, "d95eb394-c509-4d2e-9ee5-c6046b4af04b");
                _girişyap1Info = new RepoItemInfo(this, "GirişYap1", ".//div[#'login-register']//form[@action='https://www.trendyol.com/giris?cb=https%3A%2F%2Fwww.trendyol.com%2F']/?/?/span[@innertext='Giriş Yap']", ".//div[#'login-register']//form/button/span[@innertext='Giriş Yap']", 30000, null, "6b8d8376-4eb6-40cd-b539-a93c3280612a");
                _trendyolcollectionsezonsonufırsatlInfo = new RepoItemInfo(this, "TrendyolCollectionSezonSonuFırsatl", ".//div[#'browsing-gw-homepage']/div/div[2]/div[1]/div[1]/article[1]/a[@href>'https://www.trendyol.com/']/?/?/img[@alt>'Trendyol Collection - Sezon']", ".//div[#'browsing-gw-homepage']//img[@alt>'Trendyol Collection - Sezon']", 30000, null, "10eeac9f-1fac-4fd7-b961-add557cb1761");
                _fvrtbtn1Info = new RepoItemInfo(this, "FvrtBtn1", ".//div[#'boutique-detail-app']/div/div[2]/?/?/div[@title>'Mor Erkek Relaxed Fit %100']/?/?/i", ".//div[#'boutique-detail-app']//i", 30000, null, "8edac8eb-0d7f-4ad5-bc76-a3ebb2295006");
                _httpscdndsmcdncommnresize415622Info = new RepoItemInfo(this, "HttpsCdnDsmcdnComMnresize415622", ".//div[#'boutique-detail-app']//div[@title>'Mor Erkek Relaxed Fit %100']/a[@href>'https://www.trendyol.com/']/?/?/img[@src='https://cdn.dsmcdn.com/mnresize/415/622/ty327/product/media/images/20220209/9/47359369/151694335/2/2_org.jpg']", ".//div[#'boutique-detail-app']//img[@src='https://cdn.dsmcdn.com/mnresize/415/622/ty327/product/media/images/20220209/9/47359369/151694335/2/2_org.jpg']", 30000, null, "ae2d9f17-3e48-4812-88c9-cd630734469a");
                _buttontagfv1Info = new RepoItemInfo(this, "ButtonTagFv1", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[2]/div[5]/div/div/div[1]/button", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[2]/div[5]/div/div/div[1]/button", 30000, null, "d32110e9-6ad6-4091-99e6-aadb0347ac74");
                _httpscdndsmcdncommnresize4156221Info = new RepoItemInfo(this, "HttpsCdnDsmcdnComMnresize4156221", ".//div[#'boutique-detail-app']//div[@title>'Lacivert Erkek Regular Fit']/a[@href>'https://www.trendyol.com/']/?/?/img[@src='https://cdn.dsmcdn.com/mnresize/415/622/ty321/product/media/images/20220205/18/45168951/319291006/2/2_org.jpg']", ".//div[#'boutique-detail-app']//img[@src='https://cdn.dsmcdn.com/mnresize/415/622/ty321/product/media/images/20220205/18/45168951/319291006/2/2_org.jpg']", 30000, null, "9a8923cd-61d1-4970-9a91-fd566f954220");
                _iheart1Info = new IHeart1InfoClass(this);
            }

            /// <summary>
            /// The IHeart1InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("9753f8f4-a2c0-4a49-9883-4713b099dd0f")]
            public class IHeart1InfoClass : RepoItemInfo
            {
                /// <summary>
                /// IHeart1InfoClass class constructor.
                /// </summary>
                public IHeart1InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "IHeart1", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[2]/div[5]/div/div/div[1]/button/i", 30000, null, "9753f8f4-a2c0-4a49-9883-4713b099dd0f")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("23f8b29a-1e5a-44a8-ae9e-734a6af499a5")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("23f8b29a-1e5a-44a8-ae9e-734a6af499a5");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("23f8b29a-1e5a-44a8-ae9e-734a6af499a5")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("23f8b29a-1e5a-44a8-ae9e-734a6af499a5", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8386f207-1329-4cb1-ae63-ec2e115af044")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8386f207-1329-4cb1-ae63-ec2e115af044")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GirişYap item.
            /// </summary>
            [RepositoryItem("d515cc19-9ba3-4bc3-80ef-1b7a4040267f")]
            public virtual Ranorex.PTag GirişYap
            {
                get
                {
                    return _girişyapInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap item info.
            /// </summary>
            [RepositoryItemInfo("d515cc19-9ba3-4bc3-80ef-1b7a4040267f")]
            public virtual RepoItemInfo GirişYapInfo
            {
                get
                {
                    return _girişyapInfo;
                }
            }

            /// <summary>
            /// The KişiselVerileriminIşlenmesineYoenelik item.
            /// </summary>
            [RepositoryItem("e4670ff4-5639-4586-89fa-b2bc6669a355")]
            public virtual Ranorex.DivTag KişiselVerileriminIşlenmesineYoenelik
            {
                get
                {
                    return _kişiselverileriminişlenmesineyoenelikInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The KişiselVerileriminIşlenmesineYoenelik item info.
            /// </summary>
            [RepositoryItemInfo("e4670ff4-5639-4586-89fa-b2bc6669a355")]
            public virtual RepoItemInfo KişiselVerileriminIşlenmesineYoenelikInfo
            {
                get
                {
                    return _kişiselverileriminişlenmesineyoenelikInfo;
                }
            }

            /// <summary>
            /// The UEyeOl item.
            /// </summary>
            [RepositoryItem("68211e47-32b0-487a-87b9-da2357816f8a")]
            public virtual Ranorex.SpanTag UEyeOl
            {
                get
                {
                    return _ueyeolInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl item info.
            /// </summary>
            [RepositoryItemInfo("68211e47-32b0-487a-87b9-da2357816f8a")]
            public virtual RepoItemInfo UEyeOlInfo
            {
                get
                {
                    return _ueyeolInfo;
                }
            }

            /// <summary>
            /// The RegisterEmail item.
            /// </summary>
            [RepositoryItem("ac168977-9220-46c5-8c44-d95c3c7479cb")]
            public virtual Ranorex.InputTag RegisterEmail
            {
                get
                {
                    return _registeremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterEmail item info.
            /// </summary>
            [RepositoryItemInfo("ac168977-9220-46c5-8c44-d95c3c7479cb")]
            public virtual RepoItemInfo RegisterEmailInfo
            {
                get
                {
                    return _registeremailInfo;
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item.
            /// </summary>
            [RepositoryItem("d5196012-fc75-470a-8e9f-89ac0721f32a")]
            public virtual Ranorex.InputTag RegisterPasswordInput
            {
                get
                {
                    return _registerpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("d5196012-fc75-470a-8e9f-89ac0721f32a")]
            public virtual RepoItemInfo RegisterPasswordInputInfo
            {
                get
                {
                    return _registerpasswordinputInfo;
                }
            }

            /// <summary>
            /// The Fill1 item.
            /// </summary>
            [RepositoryItem("e74df106-aec3-4003-bba1-41fdb1dc56da")]
            public virtual Ranorex.UseTag Fill1
            {
                get
                {
                    return _fill1Info.CreateAdapter<Ranorex.UseTag>(true);
                }
            }

            /// <summary>
            /// The Fill1 item info.
            /// </summary>
            [RepositoryItemInfo("e74df106-aec3-4003-bba1-41fdb1dc56da")]
            public virtual RepoItemInfo Fill1Info
            {
                get
                {
                    return _fill1Info;
                }
            }

            /// <summary>
            /// The Sepetim item.
            /// </summary>
            [RepositoryItem("7725cc4e-ecda-49fd-b447-598c1672cc9e")]
            public virtual Ranorex.PTag Sepetim
            {
                get
                {
                    return _sepetimInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Sepetim item info.
            /// </summary>
            [RepositoryItemInfo("7725cc4e-ecda-49fd-b447-598c1672cc9e")]
            public virtual RepoItemInfo SepetimInfo
            {
                get
                {
                    return _sepetimInfo;
                }
            }

            /// <summary>
            /// The Favorilerim item.
            /// </summary>
            [RepositoryItem("90dd1fb2-198d-491c-a651-6ff127e43631")]
            public virtual Ranorex.PTag Favorilerim
            {
                get
                {
                    return _favorilerimInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Favorilerim item info.
            /// </summary>
            [RepositoryItemInfo("90dd1fb2-198d-491c-a651-6ff127e43631")]
            public virtual RepoItemInfo FavorilerimInfo
            {
                get
                {
                    return _favorilerimInfo;
                }
            }

            /// <summary>
            /// The AlışverişeBaşla item.
            /// </summary>
            [RepositoryItem("d4d66f08-dfa3-4906-b2d6-2b54181a5bea")]
            public virtual Ranorex.ATag AlışverişeBaşla
            {
                get
                {
                    return _alışverişebaşlaInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AlışverişeBaşla item info.
            /// </summary>
            [RepositoryItemInfo("d4d66f08-dfa3-4906-b2d6-2b54181a5bea")]
            public virtual RepoItemInfo AlışverişeBaşlaInfo
            {
                get
                {
                    return _alışverişebaşlaInfo;
                }
            }

            /// <summary>
            /// The IHeart item.
            /// </summary>
            [RepositoryItem("c982d990-ac34-4282-a517-8202680d0f5b")]
            public virtual Ranorex.ITag IHeart
            {
                get
                {
                    return _iheartInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IHeart item info.
            /// </summary>
            [RepositoryItemInfo("c982d990-ac34-4282-a517-8202680d0f5b")]
            public virtual RepoItemInfo IHeartInfo
            {
                get
                {
                    return _iheartInfo;
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComMnresize200200 item.
            /// </summary>
            [RepositoryItem("2927de92-fb85-415b-b2b2-856b04ef9d38")]
            public virtual Ranorex.ImgTag HttpsCdnDsmcdnComMnresize200200
            {
                get
                {
                    return _httpscdndsmcdncommnresize200200Info.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComMnresize200200 item info.
            /// </summary>
            [RepositoryItemInfo("2927de92-fb85-415b-b2b2-856b04ef9d38")]
            public virtual RepoItemInfo HttpsCdnDsmcdnComMnresize200200Info
            {
                get
                {
                    return _httpscdndsmcdncommnresize200200Info;
                }
            }

            /// <summary>
            /// The FeaturedFv item.
            /// </summary>
            [RepositoryItem("e9f3b9c8-51df-4cc2-8ae3-5a4ee1b6923e")]
            public virtual Ranorex.ButtonTag FeaturedFv
            {
                get
                {
                    return _featuredfvInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The FeaturedFv item info.
            /// </summary>
            [RepositoryItemInfo("e9f3b9c8-51df-4cc2-8ae3-5a4ee1b6923e")]
            public virtual RepoItemInfo FeaturedFvInfo
            {
                get
                {
                    return _featuredfvInfo;
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComMnresize500500 item.
            /// </summary>
            [RepositoryItem("39cdfe03-7a8d-4a37-b71e-2c0b7ca1231d")]
            public virtual Ranorex.ImgTag HttpsCdnDsmcdnComMnresize500500
            {
                get
                {
                    return _httpscdndsmcdncommnresize500500Info.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComMnresize500500 item info.
            /// </summary>
            [RepositoryItemInfo("39cdfe03-7a8d-4a37-b71e-2c0b7ca1231d")]
            public virtual RepoItemInfo HttpsCdnDsmcdnComMnresize500500Info
            {
                get
                {
                    return _httpscdndsmcdncommnresize500500Info;
                }
            }

            /// <summary>
            /// The FvrtBtn item.
            /// </summary>
            [RepositoryItem("d8746459-fba3-40bc-aa86-a4a8abe46794")]
            public virtual Ranorex.ITag FvrtBtn
            {
                get
                {
                    return _fvrtbtnInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn item info.
            /// </summary>
            [RepositoryItemInfo("d8746459-fba3-40bc-aa86-a4a8abe46794")]
            public virtual RepoItemInfo FvrtBtnInfo
            {
                get
                {
                    return _fvrtbtnInfo;
                }
            }

            /// <summary>
            /// The BrowsingGwHomepage item.
            /// </summary>
            [RepositoryItem("df6c200f-fddf-447a-859e-8f59e794eb51")]
            public virtual Ranorex.DivTag BrowsingGwHomepage
            {
                get
                {
                    return _browsinggwhomepageInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BrowsingGwHomepage item info.
            /// </summary>
            [RepositoryItemInfo("df6c200f-fddf-447a-859e-8f59e794eb51")]
            public virtual RepoItemInfo BrowsingGwHomepageInfo
            {
                get
                {
                    return _browsinggwhomepageInfo;
                }
            }

            /// <summary>
            /// The UfvrtBtnWrppr item.
            /// </summary>
            [RepositoryItem("899d4b3e-3101-4c18-882d-216ddf11422e")]
            public virtual Ranorex.DivTag UfvrtBtnWrppr
            {
                get
                {
                    return _ufvrtbtnwrpprInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The UfvrtBtnWrppr item info.
            /// </summary>
            [RepositoryItemInfo("899d4b3e-3101-4c18-882d-216ddf11422e")]
            public virtual RepoItemInfo UfvrtBtnWrpprInfo
            {
                get
                {
                    return _ufvrtbtnwrpprInfo;
                }
            }

            /// <summary>
            /// The IClose item.
            /// </summary>
            [RepositoryItem("e4028100-fac7-4e3f-852d-b64114ae9177")]
            public virtual Ranorex.ITag IClose
            {
                get
                {
                    return _icloseInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IClose item info.
            /// </summary>
            [RepositoryItemInfo("e4028100-fac7-4e3f-852d-b64114ae9177")]
            public virtual RepoItemInfo ICloseInfo
            {
                get
                {
                    return _icloseInfo;
                }
            }

            /// <summary>
            /// The ButtonTagFv item.
            /// </summary>
            [RepositoryItem("e3713b84-3fe3-4ea0-81c8-71f7be2cc721")]
            public virtual Ranorex.ButtonTag ButtonTagFv
            {
                get
                {
                    return _buttontagfvInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagFv item info.
            /// </summary>
            [RepositoryItemInfo("e3713b84-3fe3-4ea0-81c8-71f7be2cc721")]
            public virtual RepoItemInfo ButtonTagFvInfo
            {
                get
                {
                    return _buttontagfvInfo;
                }
            }

            /// <summary>
            /// The Erkek item.
            /// </summary>
            [RepositoryItem("ceca5310-281f-4c32-8d60-113c0b2d9312")]
            public virtual Ranorex.ATag Erkek
            {
                get
                {
                    return _erkekInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Erkek item info.
            /// </summary>
            [RepositoryItemInfo("ceca5310-281f-4c32-8d60-113c0b2d9312")]
            public virtual RepoItemInfo ErkekInfo
            {
                get
                {
                    return _erkekInfo;
                }
            }

            /// <summary>
            /// The SepeteEkle item.
            /// </summary>
            [RepositoryItem("e8a981ae-a2a4-4b62-9e48-6508a6416b59")]
            public virtual Ranorex.DivTag SepeteEkle
            {
                get
                {
                    return _sepeteekleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle item info.
            /// </summary>
            [RepositoryItemInfo("e8a981ae-a2a4-4b62-9e48-6508a6416b59")]
            public virtual RepoItemInfo SepeteEkleInfo
            {
                get
                {
                    return _sepeteekleInfo;
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComMnresize2002001 item.
            /// </summary>
            [RepositoryItem("0554aa36-2564-48ea-8fdd-9e2109f16df3")]
            public virtual Ranorex.ImgTag HttpsCdnDsmcdnComMnresize2002001
            {
                get
                {
                    return _httpscdndsmcdncommnresize2002001Info.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComMnresize2002001 item info.
            /// </summary>
            [RepositoryItemInfo("0554aa36-2564-48ea-8fdd-9e2109f16df3")]
            public virtual RepoItemInfo HttpsCdnDsmcdnComMnresize2002001Info
            {
                get
                {
                    return _httpscdndsmcdncommnresize2002001Info;
                }
            }

            /// <summary>
            /// The SomeBodyTag item.
            /// </summary>
            [RepositoryItem("742dd232-5379-4309-b22e-378a02b4b8b8")]
            public virtual Ranorex.BodyTag SomeBodyTag
            {
                get
                {
                    return _somebodytagInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The SomeBodyTag item info.
            /// </summary>
            [RepositoryItemInfo("742dd232-5379-4309-b22e-378a02b4b8b8")]
            public virtual RepoItemInfo SomeBodyTagInfo
            {
                get
                {
                    return _somebodytagInfo;
                }
            }

            /// <summary>
            /// The LoginEmail item.
            /// </summary>
            [RepositoryItem("d95eb394-c509-4d2e-9ee5-c6046b4af04b")]
            public virtual Ranorex.InputTag LoginEmail
            {
                get
                {
                    return _loginemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginEmail item info.
            /// </summary>
            [RepositoryItemInfo("d95eb394-c509-4d2e-9ee5-c6046b4af04b")]
            public virtual RepoItemInfo LoginEmailInfo
            {
                get
                {
                    return _loginemailInfo;
                }
            }

            /// <summary>
            /// The GirişYap1 item.
            /// </summary>
            [RepositoryItem("6b8d8376-4eb6-40cd-b539-a93c3280612a")]
            public virtual Ranorex.SpanTag GirişYap1
            {
                get
                {
                    return _girişyap1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap1 item info.
            /// </summary>
            [RepositoryItemInfo("6b8d8376-4eb6-40cd-b539-a93c3280612a")]
            public virtual RepoItemInfo GirişYap1Info
            {
                get
                {
                    return _girişyap1Info;
                }
            }

            /// <summary>
            /// The TrendyolCollectionSezonSonuFırsatl item.
            /// </summary>
            [RepositoryItem("10eeac9f-1fac-4fd7-b961-add557cb1761")]
            public virtual Ranorex.ImgTag TrendyolCollectionSezonSonuFırsatl
            {
                get
                {
                    return _trendyolcollectionsezonsonufırsatlInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The TrendyolCollectionSezonSonuFırsatl item info.
            /// </summary>
            [RepositoryItemInfo("10eeac9f-1fac-4fd7-b961-add557cb1761")]
            public virtual RepoItemInfo TrendyolCollectionSezonSonuFırsatlInfo
            {
                get
                {
                    return _trendyolcollectionsezonsonufırsatlInfo;
                }
            }

            /// <summary>
            /// The FvrtBtn1 item.
            /// </summary>
            [RepositoryItem("8edac8eb-0d7f-4ad5-bc76-a3ebb2295006")]
            public virtual Ranorex.ITag FvrtBtn1
            {
                get
                {
                    return _fvrtbtn1Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn1 item info.
            /// </summary>
            [RepositoryItemInfo("8edac8eb-0d7f-4ad5-bc76-a3ebb2295006")]
            public virtual RepoItemInfo FvrtBtn1Info
            {
                get
                {
                    return _fvrtbtn1Info;
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComMnresize415622 item.
            /// </summary>
            [RepositoryItem("ae2d9f17-3e48-4812-88c9-cd630734469a")]
            public virtual Ranorex.ImgTag HttpsCdnDsmcdnComMnresize415622
            {
                get
                {
                    return _httpscdndsmcdncommnresize415622Info.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComMnresize415622 item info.
            /// </summary>
            [RepositoryItemInfo("ae2d9f17-3e48-4812-88c9-cd630734469a")]
            public virtual RepoItemInfo HttpsCdnDsmcdnComMnresize415622Info
            {
                get
                {
                    return _httpscdndsmcdncommnresize415622Info;
                }
            }

            /// <summary>
            /// The ButtonTagFv1 item.
            /// </summary>
            [RepositoryItem("d32110e9-6ad6-4091-99e6-aadb0347ac74")]
            public virtual Ranorex.ButtonTag ButtonTagFv1
            {
                get
                {
                    return _buttontagfv1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagFv1 item info.
            /// </summary>
            [RepositoryItemInfo("d32110e9-6ad6-4091-99e6-aadb0347ac74")]
            public virtual RepoItemInfo ButtonTagFv1Info
            {
                get
                {
                    return _buttontagfv1Info;
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComMnresize4156221 item.
            /// </summary>
            [RepositoryItem("9a8923cd-61d1-4970-9a91-fd566f954220")]
            public virtual Ranorex.ImgTag HttpsCdnDsmcdnComMnresize4156221
            {
                get
                {
                    return _httpscdndsmcdncommnresize4156221Info.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComMnresize4156221 item info.
            /// </summary>
            [RepositoryItemInfo("9a8923cd-61d1-4970-9a91-fd566f954220")]
            public virtual RepoItemInfo HttpsCdnDsmcdnComMnresize4156221Info
            {
                get
                {
                    return _httpscdndsmcdncommnresize4156221Info;
                }
            }

            /// <summary>
            /// The IHeart1 item.
            /// </summary>
            [RepositoryItem("9753f8f4-a2c0-4a49-9883-4713b099dd0f")]
            public virtual Ranorex.ITag IHeart1
            {
                get
                {
                    return _iheart1Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IHeart1 item info.
            /// </summary>
            [RepositoryItemInfo("9753f8f4-a2c0-4a49-9883-4713b099dd0f")]
            public virtual IHeart1InfoClass IHeart1Info
            {
                get
                {
                    return _iheart1Info;
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComUyelikcbEqhttps folder.
            /// </summary>
            [RepositoryFolder("73db65c6-a8ea-4f89-a8b1-aedc2da88d56")]
            public virtual TrendyolRepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsFolder HttpsWwwTrendyolComUyelikcbEqhttps
            {
                get { return _httpswwwtrendyolcomuyelikcbeqhttps; }
            }

            /// <summary>
            /// The ProductSliderStylesModuleSliderBase folder.
            /// </summary>
            [RepositoryFolder("8538a504-da8c-4058-87d9-7e0caf40eb65")]
            public virtual TrendyolRepositoryFolders.ProductSliderStylesModuleSliderBaseFolder ProductSliderStylesModuleSliderBase
            {
                get { return _productsliderstylesmodulesliderbase; }
            }

            /// <summary>
            /// The PbMerchantGroup folder.
            /// </summary>
            [RepositoryFolder("0beba0b1-c30a-4239-97bb-d7193dd763dd")]
            public virtual TrendyolRepositoryFolders.PbMerchantGroupFolder PbMerchantGroup
            {
                get { return _pbmerchantgroup; }
            }

            /// <summary>
            /// The AccountNavItemUserLoginContainer folder.
            /// </summary>
            [RepositoryFolder("0a947112-1e8d-4dba-871f-4558462efe49")]
            public virtual TrendyolRepositoryFolders.AccountNavItemUserLoginContainerFolder AccountNavItemUserLoginContainer
            {
                get { return _accountnavitemuserlogincontainer; }
            }
        }

        /// <summary>
        /// The HttpsWwwTrendyolComUyelikcbEqhttpsFolder folder.
        /// </summary>
        [RepositoryFolder("73db65c6-a8ea-4f89-a8b1-aedc2da88d56")]
        public partial class HttpsWwwTrendyolComUyelikcbEqhttpsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _epostaInfo;
            RepoItemInfo _ueyeolInfo;
            RepoItemInfo _şifreInfo;
            RepoItemInfo _kampanyalardanhaberdarolabilmemicinkInfo;
            RepoItemInfo _qbuttonqbuttonmediumqfluidqprimaInfo;
            RepoItemInfo _fill1Info;
            RepoItemInfo _tycheckInfo;
            RepoItemInfo _codeInfo;
            RepoItemInfo _onaylaInfo;

            /// <summary>
            /// Creates a new HttpsWwwTrendyolComUyelikcbEqhttps  folder.
            /// </summary>
            public HttpsWwwTrendyolComUyelikcbEqhttpsFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpsWwwTrendyolComUyelikcbEqhttps", ".//div[#'login-register']//form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']", parentFolder, 30000, null, false, "73db65c6-a8ea-4f89-a8b1-aedc2da88d56", "")
            {
                _epostaInfo = new RepoItemInfo(this, "EPosta", "?/?/label[@innertext='E-Posta']", "", 30000, null, "aa5304c8-3e3e-4808-808e-84e86b0b6dcf");
                _ueyeolInfo = new RepoItemInfo(this, "UEyeOl", "?/?/span[@innertext='Üye Ol']", "button/span[@innertext='Üye Ol']", 30000, null, "1e303b96-25be-495c-9b83-29bb4ee65fd2");
                _şifreInfo = new RepoItemInfo(this, "Şifre", "div[2]//label[@innertext='Şifre']", "", 30000, null, "4ed839d5-a044-47b9-a3cc-6da8b3a10b0f");
                _kampanyalardanhaberdarolabilmemicinkInfo = new RepoItemInfo(this, "KampanyalardanHaberdarOlabilmemIcinK", "div[5]//span[@innertext>'Kampanyalardan haberdar olabilmem']", "", 30000, null, "935947e5-29e9-4894-a629-44b33e5ef1d0");
                _qbuttonqbuttonmediumqfluidqprimaInfo = new RepoItemInfo(this, "QButtonQButtonMediumQFluidQPrima", "button", "button", 30000, null, "6acf0e68-c725-4e34-bcc9-dddc481748bf");
                _fill1Info = new RepoItemInfo(this, "Fill1", "div[6]/div/div[1]//use[@id='Fill-1']", "div/div[1]/div/svg/g/g/g/g/use[@id='Fill-1']", 30000, null, "325df61d-f583-4ed5-a038-9606952f59da");
                _tycheckInfo = new RepoItemInfo(this, "TyCheck", "div[5]//svg", "", 30000, null, "820a6f78-b84a-4daf-a58c-0dfa0d70fff7");
                _codeInfo = new RepoItemInfo(this, "Code", "div[2]/input[@name='code']", "", 30000, null, "f71a8e65-cf9d-40ae-b496-66144addb022");
                _onaylaInfo = new RepoItemInfo(this, "Onayla", "div[3]/button[@innertext='Onayla']", "", 30000, null, "6e4f2d03-5ccb-47c1-9a24-8464dc52adf7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("73db65c6-a8ea-4f89-a8b1-aedc2da88d56")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("73db65c6-a8ea-4f89-a8b1-aedc2da88d56")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EPosta item.
            /// </summary>
            [RepositoryItem("aa5304c8-3e3e-4808-808e-84e86b0b6dcf")]
            public virtual Ranorex.LabelTag EPosta
            {
                get
                {
                    return _epostaInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The EPosta item info.
            /// </summary>
            [RepositoryItemInfo("aa5304c8-3e3e-4808-808e-84e86b0b6dcf")]
            public virtual RepoItemInfo EPostaInfo
            {
                get
                {
                    return _epostaInfo;
                }
            }

            /// <summary>
            /// The UEyeOl item.
            /// </summary>
            [RepositoryItem("1e303b96-25be-495c-9b83-29bb4ee65fd2")]
            public virtual Ranorex.SpanTag UEyeOl
            {
                get
                {
                    return _ueyeolInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl item info.
            /// </summary>
            [RepositoryItemInfo("1e303b96-25be-495c-9b83-29bb4ee65fd2")]
            public virtual RepoItemInfo UEyeOlInfo
            {
                get
                {
                    return _ueyeolInfo;
                }
            }

            /// <summary>
            /// The Şifre item.
            /// </summary>
            [RepositoryItem("4ed839d5-a044-47b9-a3cc-6da8b3a10b0f")]
            public virtual Ranorex.LabelTag Şifre
            {
                get
                {
                    return _şifreInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The Şifre item info.
            /// </summary>
            [RepositoryItemInfo("4ed839d5-a044-47b9-a3cc-6da8b3a10b0f")]
            public virtual RepoItemInfo ŞifreInfo
            {
                get
                {
                    return _şifreInfo;
                }
            }

            /// <summary>
            /// The KampanyalardanHaberdarOlabilmemIcinK item.
            /// </summary>
            [RepositoryItem("935947e5-29e9-4894-a629-44b33e5ef1d0")]
            public virtual Ranorex.SpanTag KampanyalardanHaberdarOlabilmemIcinK
            {
                get
                {
                    return _kampanyalardanhaberdarolabilmemicinkInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The KampanyalardanHaberdarOlabilmemIcinK item info.
            /// </summary>
            [RepositoryItemInfo("935947e5-29e9-4894-a629-44b33e5ef1d0")]
            public virtual RepoItemInfo KampanyalardanHaberdarOlabilmemIcinKInfo
            {
                get
                {
                    return _kampanyalardanhaberdarolabilmemicinkInfo;
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item.
            /// </summary>
            [RepositoryItem("6acf0e68-c725-4e34-bcc9-dddc481748bf")]
            public virtual Ranorex.ButtonTag QButtonQButtonMediumQFluidQPrima
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item info.
            /// </summary>
            [RepositoryItemInfo("6acf0e68-c725-4e34-bcc9-dddc481748bf")]
            public virtual RepoItemInfo QButtonQButtonMediumQFluidQPrimaInfo
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo;
                }
            }

            /// <summary>
            /// The Fill1 item.
            /// </summary>
            [RepositoryItem("325df61d-f583-4ed5-a038-9606952f59da")]
            public virtual Ranorex.UseTag Fill1
            {
                get
                {
                    return _fill1Info.CreateAdapter<Ranorex.UseTag>(true);
                }
            }

            /// <summary>
            /// The Fill1 item info.
            /// </summary>
            [RepositoryItemInfo("325df61d-f583-4ed5-a038-9606952f59da")]
            public virtual RepoItemInfo Fill1Info
            {
                get
                {
                    return _fill1Info;
                }
            }

            /// <summary>
            /// The TyCheck item.
            /// </summary>
            [RepositoryItem("820a6f78-b84a-4daf-a58c-0dfa0d70fff7")]
            public virtual Ranorex.SvgTag TyCheck
            {
                get
                {
                    return _tycheckInfo.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The TyCheck item info.
            /// </summary>
            [RepositoryItemInfo("820a6f78-b84a-4daf-a58c-0dfa0d70fff7")]
            public virtual RepoItemInfo TyCheckInfo
            {
                get
                {
                    return _tycheckInfo;
                }
            }

            /// <summary>
            /// The Code item.
            /// </summary>
            [RepositoryItem("f71a8e65-cf9d-40ae-b496-66144addb022")]
            public virtual Ranorex.InputTag Code
            {
                get
                {
                    return _codeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Code item info.
            /// </summary>
            [RepositoryItemInfo("f71a8e65-cf9d-40ae-b496-66144addb022")]
            public virtual RepoItemInfo CodeInfo
            {
                get
                {
                    return _codeInfo;
                }
            }

            /// <summary>
            /// The Onayla item.
            /// </summary>
            [RepositoryItem("6e4f2d03-5ccb-47c1-9a24-8464dc52adf7")]
            public virtual Ranorex.ButtonTag Onayla
            {
                get
                {
                    return _onaylaInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Onayla item info.
            /// </summary>
            [RepositoryItemInfo("6e4f2d03-5ccb-47c1-9a24-8464dc52adf7")]
            public virtual RepoItemInfo OnaylaInfo
            {
                get
                {
                    return _onaylaInfo;
                }
            }
        }

        /// <summary>
        /// The ProductSliderStylesModuleSliderBaseFolder folder.
        /// </summary>
        [RepositoryFolder("8538a504-da8c-4058-87d9-7e0caf40eb65")]
        public partial class ProductSliderStylesModuleSliderBaseFolder : RepoGenBaseFolder
        {
            RepoItemInfo _spantag100tlhediyekartıInfo;
            RepoItemInfo _customstampboxwrapperInfo;
            RepoItemInfo _productbranddescriptiontwolinetextInfo;
            RepoItemInfo _pricecontainerInfo;
            RepoItemInfo _descriptionfixedelementsInfo;
            RepoItemInfo _iheartwdfvrtbtnInfo;

            /// <summary>
            /// Creates a new ProductSliderStylesModuleSliderBase  folder.
            /// </summary>
            public ProductSliderStylesModuleSliderBaseFolder(RepoGenBaseFolder parentFolder) :
                    base("ProductSliderStylesModuleSliderBase", ".//div[#'browsing-gw-homepage']/div/div/div/article[6]/div/div/div[3]", parentFolder, 30000, null, false, "8538a504-da8c-4058-87d9-7e0caf40eb65", "")
            {
                _spantag100tlhediyekartıInfo = new RepoItemInfo(this, "SpanTag100TLHediyeKartı", "?/?/div[@title='100 TL Hediye Kartı']/a[@href>'https://www.trendyol.com/']/div[2]/div[1]/span[@innertext='100 TL Hediye Kartı']", "", 30000, null, "5e0f3c86-5f6a-4f81-adc2-f29c1b9fa5d9");
                _customstampboxwrapperInfo = new RepoItemInfo(this, "CustomStampBoxWrapper", "div[2]/div[@title='100 TL Hediye Kartı']/a[@href>'https://www.trendyol.com/']/div[1]/div/div[2]", "", 30000, null, "80c66075-52c6-4574-8d82-fb1f42134172");
                _productbranddescriptiontwolinetextInfo = new RepoItemInfo(this, "ProductBrandDescriptionTwoLineText", "div[2]/div[@title='100 TL Hediye Kartı']/a[@href>'https://www.trendyol.com/']/div[2]/div[1]", "", 30000, null, "a4246e0c-7d20-4b92-9a98-d5fc6a7bd78b");
                _pricecontainerInfo = new RepoItemInfo(this, "PriceContainer", "div[2]/div[@title='100 TL Hediye Kartı']/a[@href>'https://www.trendyol.com/']/div[2]/div[3]", "", 30000, null, "fd691ef8-2e63-4530-b713-8ccdefe471a2");
                _descriptionfixedelementsInfo = new RepoItemInfo(this, "DescriptionFixedElements", "?/?/div[@title='100 TL Hediye Kartı']/a[@href>'https://www.trendyol.com/']/div[2]", "", 30000, null, "d754c09f-7752-4c72-b44c-7d15b73cd01e");
                _iheartwdfvrtbtnInfo = new RepoItemInfo(this, "IHeartWdFvrtBtn", "?/?/div[@title='100 TL Hediye Kartı']/div[1]/i", "", 30000, null, "2fc675e4-af28-46da-9509-c9aa8acbb434");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8538a504-da8c-4058-87d9-7e0caf40eb65")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8538a504-da8c-4058-87d9-7e0caf40eb65")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SpanTag100TLHediyeKartı item.
            /// </summary>
            [RepositoryItem("5e0f3c86-5f6a-4f81-adc2-f29c1b9fa5d9")]
            public virtual Ranorex.SpanTag SpanTag100TLHediyeKartı
            {
                get
                {
                    return _spantag100tlhediyekartıInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTag100TLHediyeKartı item info.
            /// </summary>
            [RepositoryItemInfo("5e0f3c86-5f6a-4f81-adc2-f29c1b9fa5d9")]
            public virtual RepoItemInfo SpanTag100TLHediyeKartıInfo
            {
                get
                {
                    return _spantag100tlhediyekartıInfo;
                }
            }

            /// <summary>
            /// The CustomStampBoxWrapper item.
            /// </summary>
            [RepositoryItem("80c66075-52c6-4574-8d82-fb1f42134172")]
            public virtual Ranorex.DivTag CustomStampBoxWrapper
            {
                get
                {
                    return _customstampboxwrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CustomStampBoxWrapper item info.
            /// </summary>
            [RepositoryItemInfo("80c66075-52c6-4574-8d82-fb1f42134172")]
            public virtual RepoItemInfo CustomStampBoxWrapperInfo
            {
                get
                {
                    return _customstampboxwrapperInfo;
                }
            }

            /// <summary>
            /// The ProductBrandDescriptionTwoLineText item.
            /// </summary>
            [RepositoryItem("a4246e0c-7d20-4b92-9a98-d5fc6a7bd78b")]
            public virtual Ranorex.DivTag ProductBrandDescriptionTwoLineText
            {
                get
                {
                    return _productbranddescriptiontwolinetextInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ProductBrandDescriptionTwoLineText item info.
            /// </summary>
            [RepositoryItemInfo("a4246e0c-7d20-4b92-9a98-d5fc6a7bd78b")]
            public virtual RepoItemInfo ProductBrandDescriptionTwoLineTextInfo
            {
                get
                {
                    return _productbranddescriptiontwolinetextInfo;
                }
            }

            /// <summary>
            /// The PriceContainer item.
            /// </summary>
            [RepositoryItem("fd691ef8-2e63-4530-b713-8ccdefe471a2")]
            public virtual Ranorex.DivTag PriceContainer
            {
                get
                {
                    return _pricecontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PriceContainer item info.
            /// </summary>
            [RepositoryItemInfo("fd691ef8-2e63-4530-b713-8ccdefe471a2")]
            public virtual RepoItemInfo PriceContainerInfo
            {
                get
                {
                    return _pricecontainerInfo;
                }
            }

            /// <summary>
            /// The DescriptionFixedElements item.
            /// </summary>
            [RepositoryItem("d754c09f-7752-4c72-b44c-7d15b73cd01e")]
            public virtual Ranorex.DivTag DescriptionFixedElements
            {
                get
                {
                    return _descriptionfixedelementsInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DescriptionFixedElements item info.
            /// </summary>
            [RepositoryItemInfo("d754c09f-7752-4c72-b44c-7d15b73cd01e")]
            public virtual RepoItemInfo DescriptionFixedElementsInfo
            {
                get
                {
                    return _descriptionfixedelementsInfo;
                }
            }

            /// <summary>
            /// The IHeartWdFvrtBtn item.
            /// </summary>
            [RepositoryItem("2fc675e4-af28-46da-9509-c9aa8acbb434")]
            public virtual Ranorex.ITag IHeartWdFvrtBtn
            {
                get
                {
                    return _iheartwdfvrtbtnInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IHeartWdFvrtBtn item info.
            /// </summary>
            [RepositoryItemInfo("2fc675e4-af28-46da-9509-c9aa8acbb434")]
            public virtual RepoItemInfo IHeartWdFvrtBtnInfo
            {
                get
                {
                    return _iheartwdfvrtbtnInfo;
                }
            }
        }

        /// <summary>
        /// The PbMerchantGroupFolder folder.
        /// </summary>
        [RepositoryFolder("0beba0b1-c30a-4239-97bb-d7193dd763dd")]
        public partial class PbMerchantGroupFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tybgbeigetyborderedtycheckboxtyiInfo;
            RepoItemInfo _tycheckInfo;
            RepoItemInfo _tybgbeigetyborderedtycheckboxtyi1Info;

            /// <summary>
            /// Creates a new PbMerchantGroup  folder.
            /// </summary>
            public PbMerchantGroupFolder(RepoGenBaseFolder parentFolder) :
                    base("PbMerchantGroup", ".//div[#'pb-container']/div/div[3]", parentFolder, 30000, null, false, "0beba0b1-c30a-4239-97bb-d7193dd763dd", "")
            {
                _tybgbeigetyborderedtycheckboxtyiInfo = new RepoItemInfo(this, "TyBgBeigeTyBorderedTyCheckboxTyI", "div[2]/div[1]/div/div/div", "div[2]/div[1]/div/div/div", 30000, null, "d4634fb4-8436-46f4-99ee-37ad4442af27");
                _tycheckInfo = new RepoItemInfo(this, "TyCheck", "div[3]/div[1]//svg", "", 30000, null, "fea34503-5de7-494c-8931-ae3c56c387bd");
                _tybgbeigetyborderedtycheckboxtyi1Info = new RepoItemInfo(this, "TyBgBeigeTyBorderedTyCheckboxTyI1", "div[3]/div[1]/div/div/div", "div[3]/div[1]/div/div/div", 30000, null, "3ea5982f-2c7e-46e2-ac37-82b09166876d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0beba0b1-c30a-4239-97bb-d7193dd763dd")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0beba0b1-c30a-4239-97bb-d7193dd763dd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TyBgBeigeTyBorderedTyCheckboxTyI item.
            /// </summary>
            [RepositoryItem("d4634fb4-8436-46f4-99ee-37ad4442af27")]
            public virtual Ranorex.DivTag TyBgBeigeTyBorderedTyCheckboxTyI
            {
                get
                {
                    return _tybgbeigetyborderedtycheckboxtyiInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The TyBgBeigeTyBorderedTyCheckboxTyI item info.
            /// </summary>
            [RepositoryItemInfo("d4634fb4-8436-46f4-99ee-37ad4442af27")]
            public virtual RepoItemInfo TyBgBeigeTyBorderedTyCheckboxTyIInfo
            {
                get
                {
                    return _tybgbeigetyborderedtycheckboxtyiInfo;
                }
            }

            /// <summary>
            /// The TyCheck item.
            /// </summary>
            [RepositoryItem("fea34503-5de7-494c-8931-ae3c56c387bd")]
            public virtual Ranorex.SvgTag TyCheck
            {
                get
                {
                    return _tycheckInfo.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The TyCheck item info.
            /// </summary>
            [RepositoryItemInfo("fea34503-5de7-494c-8931-ae3c56c387bd")]
            public virtual RepoItemInfo TyCheckInfo
            {
                get
                {
                    return _tycheckInfo;
                }
            }

            /// <summary>
            /// The TyBgBeigeTyBorderedTyCheckboxTyI1 item.
            /// </summary>
            [RepositoryItem("3ea5982f-2c7e-46e2-ac37-82b09166876d")]
            public virtual Ranorex.DivTag TyBgBeigeTyBorderedTyCheckboxTyI1
            {
                get
                {
                    return _tybgbeigetyborderedtycheckboxtyi1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The TyBgBeigeTyBorderedTyCheckboxTyI1 item info.
            /// </summary>
            [RepositoryItemInfo("3ea5982f-2c7e-46e2-ac37-82b09166876d")]
            public virtual RepoItemInfo TyBgBeigeTyBorderedTyCheckboxTyI1Info
            {
                get
                {
                    return _tybgbeigetyborderedtycheckboxtyi1Info;
                }
            }
        }

        /// <summary>
        /// The AccountNavItemUserLoginContainerFolder folder.
        /// </summary>
        [RepositoryFolder("0a947112-1e8d-4dba-871f-4558462efe49")]
        public partial class AccountNavItemUserLoginContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cıkışyapInfo;
            RepoItemInfo _girişyap2Info;
            RepoItemInfo _mesutronwatgmailcomInfo;
            RepoItemInfo _initialiconiuserInfo;

            /// <summary>
            /// Creates a new AccountNavItemUserLoginContainer  folder.
            /// </summary>
            public AccountNavItemUserLoginContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("AccountNavItemUserLoginContainer", ".//div[#'account-navigation-container']/div/div[1]", parentFolder, 30000, null, false, "0a947112-1e8d-4dba-871f-4558462efe49", "")
            {
                _cıkışyapInfo = new RepoItemInfo(this, "CıkışYap", ".//button/p[@innertext='Çıkış Yap']", "", 30000, null, "ef7a6a48-6074-4373-8a5c-352b3d5ac3bb");
                _girişyap2Info = new RepoItemInfo(this, "GirişYap2", ".//div[@innertext='Giriş Yap']", "", 30000, null, "cdb69519-d74f-4aaf-a9b4-57874079fa60");
                _mesutronwatgmailcomInfo = new RepoItemInfo(this, "MesutronwAtgmailCom", ".//p[@innertext='mesutronw@gmail.com']", "", 30000, null, "510cc74d-57c2-43e3-99bd-50b2a9292162");
                _initialiconiuserInfo = new RepoItemInfo(this, "InitialIconIUser", "?/?/div/i[1]", "div[1]/div/i[1]", 30000, null, "ed335b05-3125-4466-82c4-ab06e59e1871");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0a947112-1e8d-4dba-871f-4558462efe49")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0a947112-1e8d-4dba-871f-4558462efe49")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CıkışYap item.
            /// </summary>
            [RepositoryItem("ef7a6a48-6074-4373-8a5c-352b3d5ac3bb")]
            public virtual Ranorex.PTag CıkışYap
            {
                get
                {
                    return _cıkışyapInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The CıkışYap item info.
            /// </summary>
            [RepositoryItemInfo("ef7a6a48-6074-4373-8a5c-352b3d5ac3bb")]
            public virtual RepoItemInfo CıkışYapInfo
            {
                get
                {
                    return _cıkışyapInfo;
                }
            }

            /// <summary>
            /// The GirişYap2 item.
            /// </summary>
            [RepositoryItem("cdb69519-d74f-4aaf-a9b4-57874079fa60")]
            public virtual Ranorex.DivTag GirişYap2
            {
                get
                {
                    return _girişyap2Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap2 item info.
            /// </summary>
            [RepositoryItemInfo("cdb69519-d74f-4aaf-a9b4-57874079fa60")]
            public virtual RepoItemInfo GirişYap2Info
            {
                get
                {
                    return _girişyap2Info;
                }
            }

            /// <summary>
            /// The MesutronwAtgmailCom item.
            /// </summary>
            [RepositoryItem("510cc74d-57c2-43e3-99bd-50b2a9292162")]
            public virtual Ranorex.PTag MesutronwAtgmailCom
            {
                get
                {
                    return _mesutronwatgmailcomInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The MesutronwAtgmailCom item info.
            /// </summary>
            [RepositoryItemInfo("510cc74d-57c2-43e3-99bd-50b2a9292162")]
            public virtual RepoItemInfo MesutronwAtgmailComInfo
            {
                get
                {
                    return _mesutronwatgmailcomInfo;
                }
            }

            /// <summary>
            /// The InitialIconIUser item.
            /// </summary>
            [RepositoryItem("ed335b05-3125-4466-82c4-ab06e59e1871")]
            public virtual Ranorex.ITag InitialIconIUser
            {
                get
                {
                    return _initialiconiuserInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The InitialIconIUser item info.
            /// </summary>
            [RepositoryItemInfo("ed335b05-3125-4466-82c4-ab06e59e1871")]
            public virtual RepoItemInfo InitialIconIUserInfo
            {
                get
                {
                    return _initialiconiuserInfo;
                }
            }
        }

        /// <summary>
        /// The ChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("64484701-fd89-402b-b7a0-5eb491f0e994")]
        public partial class ChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _bağlantıyıyenisekmedeacInfo;

            /// <summary>
            /// Creates a new Chrome  folder.
            /// </summary>
            public ChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Chrome", "/form[@title='']", parentFolder, 30000, null, true, "64484701-fd89-402b-b7a0-5eb491f0e994", "")
            {
                _bağlantıyıyenisekmedeacInfo = new RepoItemInfo(this, "BağlantıyıYeniSekmedeAc", "container[@accessiblename='']/menubar[@accessiblename='']//menuitem[@accessiblename>'Bağlantıyı yeni sekmede a']", ".//menuitem[@accessiblename>'Bağlantıyı yeni sekmede a']", 30000, null, "5768e15a-e693-4501-9437-859bbea31e34");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("64484701-fd89-402b-b7a0-5eb491f0e994")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("64484701-fd89-402b-b7a0-5eb491f0e994")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BağlantıyıYeniSekmedeAc item.
            /// </summary>
            [RepositoryItem("5768e15a-e693-4501-9437-859bbea31e34")]
            public virtual Ranorex.MenuItem BağlantıyıYeniSekmedeAc
            {
                get
                {
                    return _bağlantıyıyenisekmedeacInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The BağlantıyıYeniSekmedeAc item info.
            /// </summary>
            [RepositoryItemInfo("5768e15a-e693-4501-9437-859bbea31e34")]
            public virtual RepoItemInfo BağlantıyıYeniSekmedeAcInfo
            {
                get
                {
                    return _bağlantıyıyenisekmedeacInfo;
                }
            }
        }

        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder folder.
        /// </summary>
        [RepositoryFolder("5cb22cac-0e5b-4f9b-8287-241fec31be05")]
        public partial class EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _netflixhediyekodu100tlhediyekartıInfo;
            RepoItemInfo _kapatInfo;
            RepoItemInfo _yenisekmeInfo;
            RepoItemInfo _httpswwwtrendyolcomgiriscbeqhttpspInfo;
            RepoItemInfo _geriInfo;

            /// <summary>
            /// Creates a new EnTrendUEruenlerTuerkiyeninOnlineAl  folder.
            /// </summary>
            public EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EnTrendUEruenlerTuerkiyeninOnlineAl", "/form[@title>'En Trend Ürünler Türkiye''nin']", parentFolder, 30000, null, true, "5cb22cac-0e5b-4f9b-8287-241fec31be05", "")
            {
                _netflixhediyekodu100tlhediyekartıInfo = new RepoItemInfo(this, "NetflixHediyeKodu100TLHediyeKartı", "container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[@accessiblename='Google Chrome']/container/container[@accessiblerole='Pane']/container[1]/tabpagelist/container[1]/?/?/tabpage[@accessiblename>'Netflix Hediye Kodu 100 TL']", ".//tabpage[@accessiblename>'Netflix Hediye Kodu 100 TL']", 30000, null, "7b029fec-f741-4980-ade3-a2c9368a06a9");
                _kapatInfo = new RepoItemInfo(this, "Kapat", "container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[@accessiblename='Google Chrome']//tabpagelist/container[1]/?/?/tabpage[@accessiblerole='PageTab' and @title>'En Trend Ürünler Türkiye''nin' and @index='0']/button[@accessiblename='Kapat']", ".//tabpage[@accessiblerole='PageTab' and @title>'En Trend Ürünler Türkiye''nin' and @index='0']/button[@accessiblename='Kapat']", 30000, null, "f5c2cbc6-dfad-411d-8035-05d0c9dae600");
                _yenisekmeInfo = new RepoItemInfo(this, "YeniSekme", "container[@accessiblename>'https://www.trendyol.com/']/container[@accessiblename='Google Chrome']/container/container[@accessiblerole='Pane']/container[1]/?/?/button[@accessiblename='Yeni Sekme']", ".//button[@accessiblename='Yeni Sekme']", 30000, null, "f76e6d08-7d76-4b66-b798-ea73a43caab1");
                _httpswwwtrendyolcomgiriscbeqhttpspInfo = new RepoItemInfo(this, "HttpsWwwTrendyolComGiriscbEqhttpsP", "container[@accessiblename>'Gelen Kutusu (2) - mesutronw@gmail.com']/container[@accessiblename='Google Chrome']/container/container[@accessiblerole='Pane']/container[1]/tabpagelist/container[1]/?/?/tabpage[@accessiblename>'https://www.trendyol.com/']", ".//tabpage[@accessiblename>'https://www.trendyol.com/']", 30000, null, "2e22d0c0-e0f5-4bce-8de7-81d1efea701d");
                _geriInfo = new RepoItemInfo(this, "Geri", "container[@accessiblename>'Favoriler - Trendyol - Google']/container[@accessiblename='Google Chrome']//toolbar[@accessiblerole='ToolBar']/button[@accessiblename='Geri']", ".//button[@accessiblename='Geri']", 30000, null, "da2e4ce9-c63e-4190-b740-c7d1f1952e4a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5cb22cac-0e5b-4f9b-8287-241fec31be05")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5cb22cac-0e5b-4f9b-8287-241fec31be05")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NetflixHediyeKodu100TLHediyeKartı item.
            /// </summary>
            [RepositoryItem("7b029fec-f741-4980-ade3-a2c9368a06a9")]
            public virtual Ranorex.TabPage NetflixHediyeKodu100TLHediyeKartı
            {
                get
                {
                    return _netflixhediyekodu100tlhediyekartıInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The NetflixHediyeKodu100TLHediyeKartı item info.
            /// </summary>
            [RepositoryItemInfo("7b029fec-f741-4980-ade3-a2c9368a06a9")]
            public virtual RepoItemInfo NetflixHediyeKodu100TLHediyeKartıInfo
            {
                get
                {
                    return _netflixhediyekodu100tlhediyekartıInfo;
                }
            }

            /// <summary>
            /// The Kapat item.
            /// </summary>
            [RepositoryItem("f5c2cbc6-dfad-411d-8035-05d0c9dae600")]
            public virtual Ranorex.Button Kapat
            {
                get
                {
                    return _kapatInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Kapat item info.
            /// </summary>
            [RepositoryItemInfo("f5c2cbc6-dfad-411d-8035-05d0c9dae600")]
            public virtual RepoItemInfo KapatInfo
            {
                get
                {
                    return _kapatInfo;
                }
            }

            /// <summary>
            /// The YeniSekme item.
            /// </summary>
            [RepositoryItem("f76e6d08-7d76-4b66-b798-ea73a43caab1")]
            public virtual Ranorex.Button YeniSekme
            {
                get
                {
                    return _yenisekmeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The YeniSekme item info.
            /// </summary>
            [RepositoryItemInfo("f76e6d08-7d76-4b66-b798-ea73a43caab1")]
            public virtual RepoItemInfo YeniSekmeInfo
            {
                get
                {
                    return _yenisekmeInfo;
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComGiriscbEqhttpsP item.
            /// </summary>
            [RepositoryItem("2e22d0c0-e0f5-4bce-8de7-81d1efea701d")]
            public virtual Ranorex.TabPage HttpsWwwTrendyolComGiriscbEqhttpsP
            {
                get
                {
                    return _httpswwwtrendyolcomgiriscbeqhttpspInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComGiriscbEqhttpsP item info.
            /// </summary>
            [RepositoryItemInfo("2e22d0c0-e0f5-4bce-8de7-81d1efea701d")]
            public virtual RepoItemInfo HttpsWwwTrendyolComGiriscbEqhttpsPInfo
            {
                get
                {
                    return _httpswwwtrendyolcomgiriscbeqhttpspInfo;
                }
            }

            /// <summary>
            /// The Geri item.
            /// </summary>
            [RepositoryItem("da2e4ce9-c63e-4190-b740-c7d1f1952e4a")]
            public virtual Ranorex.Button Geri
            {
                get
                {
                    return _geriInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Geri item info.
            /// </summary>
            [RepositoryItemInfo("da2e4ce9-c63e-4190-b740-c7d1f1952e4a")]
            public virtual RepoItemInfo GeriInfo
            {
                get
                {
                    return _geriInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("bc875d7d-f7bd-4bec-ba01-9500f0022fa6")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _hoparloerpercent100Info;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "bc875d7d-f7bd-4bec-ba01-9500f0022fa6", "")
            {
                _hoparloerpercent100Info = new RepoItemInfo(this, "HoparloerPercent100", ".//toolbar[@controlid='1504' and @controlname='Kullanıcı Yükseltmesi Bildirim Alanı']/button[@text='Hoparlör: %100']", ".//button[@text='Hoparlör: %100']", 30000, null, "5a4adfc1-b56e-43ac-ac0c-4882b2ecc7ae");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bc875d7d-f7bd-4bec-ba01-9500f0022fa6")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bc875d7d-f7bd-4bec-ba01-9500f0022fa6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HoparloerPercent100 item.
            /// </summary>
            [RepositoryItem("5a4adfc1-b56e-43ac-ac0c-4882b2ecc7ae")]
            public virtual Ranorex.Button HoparloerPercent100
            {
                get
                {
                    return _hoparloerpercent100Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The HoparloerPercent100 item info.
            /// </summary>
            [RepositoryItemInfo("5a4adfc1-b56e-43ac-ac0c-4882b2ecc7ae")]
            public virtual RepoItemInfo HoparloerPercent100Info
            {
                get
                {
                    return _hoparloerpercent100Info;
                }
            }
        }

        /// <summary>
        /// The Explorer1AppFolder folder.
        /// </summary>
        [RepositoryFolder("1a01c20e-c9ff-4a6b-9f5f-bbfda8eb32b9")]
        public partial class Explorer1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _list1Info;

            /// <summary>
            /// Creates a new Explorer1  folder.
            /// </summary>
            public Explorer1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer1", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "1a01c20e-c9ff-4a6b-9f5f-bbfda8eb32b9", "")
            {
                _list1Info = new RepoItemInfo(this, "List1", "?/?/list[@automationid='1']", "?/?/list[@automationid='1']", 30000, null, "31b4b110-f209-4a45-9d3d-5553523ffd6c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1a01c20e-c9ff-4a6b-9f5f-bbfda8eb32b9")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1a01c20e-c9ff-4a6b-9f5f-bbfda8eb32b9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The List1 item.
            /// </summary>
            [RepositoryItem("31b4b110-f209-4a45-9d3d-5553523ffd6c")]
            public virtual Ranorex.List List1
            {
                get
                {
                    return _list1Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The List1 item info.
            /// </summary>
            [RepositoryItemInfo("31b4b110-f209-4a45-9d3d-5553523ffd6c")]
            public virtual RepoItemInfo List1Info
            {
                get
                {
                    return _list1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
